Documentation for Hypothermia System
Terasology/ClimateConditions pull request #12
Opened 2020-06-01 14:08 UTC by ktksan

2020-06-03 21:16 UTC, jdrueckert requested changes
Left a bunch of suggestions - not because your doc comments where bad in general, but because they felt less concise than they could be and because I didn't find a good way of how to generally describe ho to get them there :see_no_evil: 
Please tell me if in the future you'd rather get a "maybe rather go in that direction" instead of precise suggestions and I'll try to explain :sweat_smile:

2020-06-03 21:16 UTC, jdrueckert commented on src/main/java/org/terasology/climateConditions/VisibleBreathComponent.java
>  }
```suggestion
}

```

2020-06-03 21:16 UTC, jdrueckert commented on src/main/java/org/terasology/climateConditions/FrostbiteSystem.java
> + */
```suggestion
/**
 * Adds frostbite to the player.
 * Frostbite is a periodic effect that, e.g., damages and stuns the player.
 * Is only active iff the player has a {@link HypothermiaComponent}.
 */
```

With "iff" being "if and only if".

2020-06-03 21:16 UTC, jdrueckert commented on src/main/java/org/terasology/climateConditions/HypothermiaComponent.java
> + */
```suggestion
/**
 * Increases the game difficulty in locations with extreme cold climate.
 * Is added/removed by the {@link HypothermiaSystem} when the player enters/leaves a "danger zone".
 */
```

2020-06-03 21:16 UTC, jdrueckert commented on src/main/java/org/terasology/climateConditions/HypothermiaSystem.java
> + */
```suggestion
/**
 * Adds a {@link HypothermiaComponent} to the player.
 * Hypothermia occurs in locations with extremely cold climate and, e.g., slows the player's movements.
 */
```

2020-06-03 21:16 UTC, jdrueckert commented on src/main/java/org/terasology/climateConditions/HypothermiaSystem.java
> +     */
```suggestion
    /**
     * Modifies the walking/running speed of the player.
     * Is only active iff the player has a {@link HypothermiaComponent}.
     */
```

2020-06-03 21:16 UTC, jdrueckert commented on src/main/java/org/terasology/climateConditions/HypothermiaSystem.java
> +     */
```suggestion
    /**
     * Modifies the jump speed of the player.
     * Is only active iff the player has a {@link HypothermiaComponent}.
     */
```

2020-06-03 21:16 UTC, jdrueckert commented on src/main/java/org/terasology/climateConditions/VisibleBreathComponent.java
> + */
```suggestion
/**
 * Augments the world with a visible breath particle effect.
 * Is added/updated by the {@link VisibleBreathingSystem} periodically.
 */
```

2020-06-03 21:16 UTC, jdrueckert commented on src/main/java/org/terasology/climateConditions/VisibleBreathingSystem.java
> + */
```suggestion
/**
 * Adds a {@link VisibleBreathComponent} to the player.
 * Visible breath is a periodic action adding a visible breath particle effect.
 * Is active only iff the player has a {@link HypothermiaComponent}
 */
```

Actually when thinking about this and the "increases difficulty" part of the hypothermia component, I realized, that visible breath should be decoupled from hypothermia. Hypothermia is an "illness" that negatively affects a player - visible breath is independent of that and appears whenever it is cold enough, independent of whether or not the player has hypothermia.

2020-06-04 09:53 UTC, ktksan commented
I'm sorry 😅😅 I wasn't really sure about what kind of docs should be written, I just looked at the comments in BlockDamageComponent, etc.. and then wrote it like that.... I will try to make it concise next time.

2020-06-04 19:19 UTC, skaldarnar reviewed
When writing documentation I try to look at the code as somebody who has a general understanding of the framework (e.g., knows what an entity or component is), but has no clue what the specific systems, etc. are doing. 

After writing down the first doc comments I go back and read them to me - do they give me more information than I had before? Do they comments raise more questions? 

A good example is "modifies" or "adjusts" - these verbs should be accompanied by an explanation, or better be replaced by more concrete wording. For instance, "modifies speed to be slower" could become "slows down", and instead of "adjust the modifier" you could clarify that "adjust speed modifier according to time spent in the danger zone".

2020-06-04 19:19 UTC, skaldarnar commented on src/main/java/org/terasology/climateConditions/HypothermiaSystem.java
> +     * Modifies the walking/running speed of the player.
Well, that `modifySpeed` modifies the speed should be no surprise. However, in what way does it modify it? In particular, we are **decreasing** the **walk speed**.

2020-06-04 19:19 UTC, skaldarnar commented on src/main/java/org/terasology/climateConditions/HypothermiaSystem.java
> +     * Modifies the jump speed of the player.
Same as above:  `modifyJumpSpeed` modifies the jump speed - no surprises there. But in what way? Another clue here might be the fact that we are not modifying any physical ability of the character but reacting to the respective events.

2020-06-04 19:19 UTC, skaldarnar commented on src/main/java/org/terasology/climateConditions/VisibleBreathComponent.java
> + * Augments the world with a visible breath particle effect.
"Augments the world" sounds a bit ... broad and unspecific. I'd be a bit more specific and explain that this only has the desired effect if the entity also has a `LocationComponent` that determines the location and direction of the effect.

2020-06-06 21:14 UTC, jdrueckert approved these changes

2020-06-06 21:14 UTC, merged